#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-cells-erb
Version  : 0.0.9
Release  : 9
URL      : https://rubygems.org/downloads/cells-erb-0.0.9.gem
Source0  : https://rubygems.org/downloads/cells-erb-0.0.9.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
# Cells::Erb
Proper ERB support for Cells using [Erbse](https://github.com/apotonick/erbse).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n cells-erb-0.0.9
gem spec %{SOURCE0} -l --ruby > rubygem-cells-erb.gemspec

%build
export LANG=C
gem build rubygem-cells-erb.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
cells-erb-0.0.9.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/cells-erb-0.0.9.gem
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/README.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/cells-erb.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/gemfiles/rails_4.2-tilt-1.4.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/gemfiles/rails_4.2-tilt-2.0.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/gemfiles/rails_4.2-tilt-3.0.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/lib/cell/erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/lib/cell/erb/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/lib/cell/erb/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/lib/cells-erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song/render_in_render.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song/render_in_render_2.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song/with_content_tag.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song/with_content_tag_and_content_tag.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song/with_form_for_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song/with_form_tag_and_content_tag.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/cells/song_cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config.ru
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config/application.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config/boot.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config/database.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config/locales/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/dummy/config/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/erb_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-erb-0.0.9/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/cells-erb-0.0.9.gemspec
